// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://tktjjxgxvzzvgnmeodqg.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6InRrdGpqeGd4dnp6dmdubWVvZHFnIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NjEzMjIwMzcsImV4cCI6MjA3Njg5ODAzN30.ocZAriw2sAR-IQzk2iCxRy730HxAkmzEp8CvuQUQaJc";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY, {
  auth: {
    storage: localStorage,
    persistSession: true,
    autoRefreshToken: true,
  }
});